language: php

dist: trusty

matrix:
  include:
  - php: 7.3
    env: ANALYSIS='true'
  - php: nightly

  allow_failures:
  - php: nightly

before_script:
- composer require php-coveralls/php-coveralls:^2.2.0
- composer install -n

after_success:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi

steps:
  - checkout
  - run:
     name: "Run tests"
     command: phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report
  - store_artifacts:
      path:  build/coverage-report
