language: php

dist: trusty

matrix:
  include:
  - php: 7.3
    env: ANALYSIS='true'
  - php: nightly

  allow_failures:
  - php: nightly

before_script:
- composer require php-coveralls/php-coveralls:^2.2.0
- composer install -n

after_success:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi

- step:
  name: Run tests and Generate coverage reports
  image: epcallan/php7-testing-phpunit:7.2-phpunit7
  caches:
   - composer
  script:
   - composer install --no-progress --no-suggest
   - vendor/bin/phpunit
- step:
   name: Sonar check quality code
   script:
     - pipe: sonarsource/sonarcloud-scan:1.0.0
       variables:
         EXTRA_ARGS: -Dsonar.projectDescription=\"Project with sonarcloud-scan pipe\" -Dsonar.eslint.reportPaths=\"report.json\" -Dsonar.php.coverage.reportPaths=\"codeCoverage/coverage.xml\" -Dsonar.php.tests.reportPath=\"codeCoverage/test.xml\"
         SONAR_SCANNER_OPTS: -Xmx512m
         DEBUG: "false"
